Am 306 ap is exception handling
hmcts/am-lib pull request #200
Opened 2019-05-30 12:13 UTC by abhijitdiwan

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/AM-306

### Change description ###
APIs Exception Handling and Swagger Support

2019-05-31 09:20 UTC, shashank-rastogi requested changes

2019-05-31 09:22 UTC, abhijitdiwan commented on am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ExplicitAccessGrant.java
> +@JsonDeserialize(builder = ExplicitAccessGrant.ExplicitAccessGrantBuilder.class)
You mean change description? if yes updated

2019-05-31 09:26 UTC, abhijitdiwan commented on src/main/java/uk/gov/hmcts/reform/amapi/controllers/AmLibProxyController.java
> +        @ApiResponse(code = 500, message = "Internal server error")
Tested this and I have not get 404 comes when url is like filter-resource. Only get 404 when I got invalid URL. (eg. /invalidUrl or /invalidFiterResource)

2019-05-31 09:39 UTC, abhijitdiwan commented on src/main/java/uk/gov/hmcts/reform/amapi/util/ErrorConstants.java
> +
seems PMD ask for class Avoid constants in interfaces. Interfaces define types, constants are implementation details better placed in classes or enums. See Effective Java, item 19.

2019-05-31 11:08 UTC, abhijitdiwan commented on src/main/java/uk/gov/hmcts/reform/amapi/controllers/AmLibProxyController.java
> +        @ApiResponse(code = 400, message = "Incomplete request information or Malformed input request"),
updated

2019-05-31 11:08 UTC, abhijitdiwan commented on src/test/java/uk/gov/hmcts/reform/amapi/controller/ControllerTest.java
> +import com.fasterxml.jackson.core.JsonPointer;
done

2019-05-31 11:08 UTC, abhijitdiwan commented on src/test/java/uk/gov/hmcts/reform/amapi/controller/ControllerExceptionAdviceTest.java
> +            + "      \"resourceType\": \"case\",\n"
done

2019-05-31 11:08 UTC, abhijitdiwan commented on src/test/java/uk/gov/hmcts/reform/amapi/controller/ControllerExceptionAdviceTest.java
> +package uk.gov.hmcts.reform.amapi.controller;
done

2019-06-03 17:22 UTC, shashank-rastogi approved these changes

2019-06-03 17:22 UTC, merged